### ISSUE TITLE
'artillery-plugin-' prefix not flexible for private plugin naming conventions

### ISSUE THREAD

**Issue by cppbit** [shoreditch-ops/artillery-core#108]
What's the reason for having the

**Comment by hassy** [comment]
The reason is zero-config discovery of plugins, i.e. as a user you just need to add the name of the plugin + its settings to your test script, and Artillery will know how to load it.

Can you give a bit more detail on why that doesn't work for private plugins?

**Comment by cppbit** [comment]
We package our custom packages in scopes/namespaces, e.g. @organization_name/package_name because there could be a clashing name in some of our registered repositories. Enforcing the prefix "artillery-plugin-" suggests there would be a universal distinct list of package names which is not always the case, take an example with artillery on github, its https://github.com/shoreditch-ops/artillery instead of https://github.com/artillery because many people/namespaces can have the same name.

I need to be sure at all times that when I run npm install, my custom package will be loaded. 
I suggest the code below just read the plugin name as provided

```
...
    let requireString = 'artillery-plugin-' + pluginName;
    let Plugin, plugin;
    try {
      Plugin = require(requireString);
...
```

**Comment by hassy** [comment]
Cool. Will gladly accept a PR which allows something like:

```yaml
config:
  plugins:
    some-custom-plugin:
      package: "@prefix/some-package-name"
      option1: "something"
      option2: "somethingElse"
scenarios:
  # ...
```

To load the plugin from `@prefix/some-package-name` rather than `artillery-plugin-some-custom-plugin`.
