### ISSUE TITLE
Be able to include a scenario in another

### ISSUE THREAD

**Issue by steveschnepp** [shoreditch-ops/artillery-core#122]
I'm currently writing several scenarios, which are highly similar. It would be nice to be able to _include_ one in another.

**Comment by hassy** [comment]
[YAML references](https://gist.github.com/bowsersenior/979804) can be used for this.

For example, something like:

```yaml

#
# this can be anywhere in the YAML file that defines the test:
#
subflow-add-book-to-cart: &subflow-add-book-to-cart
  - post:
      url: "/cart/items"
      headers:
        "content-type": "application/x-www-form-urlencoded"
      form:
        name: "{{ name }}"
        product_slug: "book"
        inscription: "{{ dedication }}"
        gift_options: "{{ gift_option }}"
  - get:
      url: "/cart"
      afterResponse:
        - "checkCartContents"

#
# Then in a scenario definition we can do:
#
scenarios:
  - name: "Find and buy a book"
    flow:
      - get:
          url: "/"
      # more steps here...
      
      # now include the steps defined above:
      - *subflow-add-book-to-cart
```
