### ISSUE TITLE
Make namespaces configureable per emit action

### ISSUE THREAD

**Issue by menzow** [shoreditch-ops/artillery-core#124]
Hey,

First of all, thank you for this tool. Best load tester I could find for testing Web Sockets. 👍 

I started using Artillery yesterday, and due to the structure of my application it's required to communicate in multiple [namespaces](http://socket.io/docs/rooms-and-namespaces/) at the same time. 

While digging through the documentation I wasn't able to figure out an existing way to do this, so I added this feature to the `SocketIoEngine`.

I added a new optional attribute to the `emit` action called `namespace`. Here you can enter the namespace you want the socket to communicate in for that specific action. Namespace socket connections are scoped to the scenario context and are only established once per scenario. 

Once a scenario has been completed, all socket connections in its context are disconnected through the `SocketIoEngine::closeContextSockets(context)` method.

Example config:
```
config:
  target: http://localhost:1337
  phases:
  - duration: 60
    arrivalRate: 50
scenarios:
- engine: socketio
  flow:
  #Authenticate namespaces
  - emit:
      namespace: "/nsp1"
      channel: "authenticate"
      data:
        token: authtoken
  - emit:
      namespace: "/nsp2"
      channel: "authenticate"
      data:
        token: authtoken
```

Compare changes:
https://github.com/shoreditch-ops/artillery-core/compare/master...menzow:master
