### ISSUE TITLE
Feature Proposal: File Upload

### ISSUE THREAD

**Issue by zcei** [shoreditch-ops/artillery-core#146]
Hej guys,

I'd love to use artillery for testing file uploads as well. I *do* know there's an open issue (https://github.com/shoreditch-ops/artillery/issues/106).

But as this is a thing that needs to be implemented here, plus I couldn't find an already discussed proposal.
I'd love to get some feedback, as I want start working on this 🙃 

<hr>

# File Upload

## Rationale

Uploading files is a frequent HTTP use-case, but currently not supported very well within `artillery-core`.

To enable user to follow a unified approach, this proposal adds a cURL-style way of indicating file uploads.

In the background each file be passed to `request` using a `ReadableStream` to allow tests with potentially huge file sizes.

## Changes

Indicate file payload by prepending the path with `@`, e.g. `@path/to/file.md`.

**Input types:**

* single file
* list of files
* list of objects with `key` and `path` values (form multipart)

**File resolution:**

If the `@` sign (file indicator) is immediately followed by a `/`, file resolution happens from root of disk.

Otherwise files will be tried to be resolved in following order:

1. `process.cwd` + your path
2. `__dirname` + your path

**Backwards compatibility: :warning:**

People who previously started their custom body payload with an at-sign (`@`) will need to adjust their descriptors.

I can't really figure, why you would do that - but as it wasn't disallowed previously I'd rather go with a semver valid major bump / breaking change.

## Examples of Input

**Single File**

```yaml
post:
  url: "/test"
  body: "@selfie.jpg"
```

**Multiple Files**

```yaml
post:
  url: "/test"
  body:
    - "@selfie.jpg"
    - "@selfie2.png"
```

**Multiple Files - Multipart Form**

```yaml
post:
  url: "/test"
  body:
    - key: foo
      path: "@selfie.jpg"
    - key: bar
      path: "@selfie2.png"
```

**Comment by zcei** [comment]
Thinking further about this, taking the same approach as the `payload` feature makes file resolution way easier and therefore leads to a more straight forward implementation.

Basically, one would set a `files` property in the config, containing an array of variable names, referencing the files in the order they were put in.

**Examples**

```sh
/Users/example$ artillery run my_test.json -f some.jpg -p pets.csv -f random.zip 
```

```yaml
config:
  payload:
    fields:
      - "species"
      - "name"
  files:
    - "image"
    - "archive"
```

```yaml
post:
  url: "/pets/{{ species }}/{{ name }}"
  body: {{ @image }}
```
