### ISSUE TITLE
Artillery does not return with certain malformed requests

### ISSUE THREAD

**Issue by gcuni** [shoreditch-ops/artillery-core#151]
Sometimes when capturing variables to be used in follow up calls, the capture can end up being empty for a number of reasons. If that happens, the url is empty in requestParams and the request library throws an exception that is not handled by artillery-core. 
A simple fix for this can be checking that requestParams has a url before calling request(). I will submit a pull request that addresses this. This is an issue for people using this in ci/cd systems as a single bad test request can cause artillery to hang forever. Here's a simple script to repro with intentional errors in it:
```yaml
config:
  target: https://aws.amazon.com
  phases:
    - duration: 20
      arrivalRate: 4

scenarios:
  -
    flow:
      -
        get:
          url: /
          capture:
            -
              json: "$.view.details"
              as: c0
        get:
          url: "{{c0}}"
```
