### ISSUE TITLE
beforeReqeust's requestParams can't be customized.

### ISSUE THREAD

**Issue by outsideris** [shoreditch-ops/artillery-core#187]
```
- post:
    url: '/login'
    beforeRequest: 'setDeviceAsJson'
    json:
      grant_type: 'password'
      email: '{{ username }}'
      password: '{{ password }}'
      device: '{{ device }}'
```

In here, `device` is JSON, but the request stringifies it. So, I want to customize `device` in `beforeRequest` hook.

As the [document](https://artillery.io/docs/testing_http.html#http-specific-configuration), `requestParams` object is for it.

> requestParams is an object given to the Request library. Use this parameter to customize what is sent in the request (headers, body, cookies etc)

```
// process.js
module.exports = {
  setDeviceAsJson: (requestParams, context, ee, next) => {
    requestParams.json.device = JSON.parse(context.vars.device);
    return next();
  },
};
```

However, reqeust's json wasn't changed, even if `requestParams` was changed.

In [here](https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_http.js#L202), `requestParams` is overwritten after running `beforeRequest` hook. This change was introduced in [this commit](https://github.com/shoreditch-ops/artillery-core/commit/405b78ec534b7c484555eeadfffdb5db0e87654c), but I can't understand what your intention is.

`requestParams` looks useless in the hook.
