### ISSUE TITLE
supporting multipart form data

### ISSUE THREAD

**Issue by cskru** [shoreditch-ops/artillery-core#219]
Aren't you passing formData with read stream?
Like this:
```javascript
           formData: {
                foo: {
                    value: fs.createReadStream(filePath),
                    options: {
                        filename: fileName,
                        contentType: 'application/octet-stream'
                    }
                }
            }
```

This is how formData works..
I tried this:
```yaml
config:
  target: 'http://localhost:8000'
  files:
    - "@../file.json"
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - flow:
    - post:
        url: "/bla"
        formData:
          foo:  "@../file.json"
```

Is my spec right?
Do I need to add something to it?
My server gives 400 bad request as it is unable to find foo.

This is a perfectly working api and is tested functionally. There is some issue with the way in which formData is sent via request.

Any help is much appreciated.
