### ISSUE TITLE
Not able to send Form Data with request

### ISSUE THREAD

**Issue by jwingo1015** [shoreditch-ops/artillery-core#59]
Im not able to use artillery.io to send form data with a post request for my test. I have used the following with no luck:
json: "firstName': 'Jerry', 'lastName':'Winston', 'zipCode': '12345', 'expertiseLevel': 'BEGINNER'}"
        headers:
          authorization: "Bearer {{access_token}}"
          content-type: "multipart/form-data, boundary=------WebKitFormBoundaryKPzoKfSfBvBzfvZa"
          accept: "application/json"

Also I have tried the following with no luck:
formData: "firstName': 'Jerry', 'lastName':'Winston', 'zipCode': '12345', 'expertiseLevel': 'BEGINNER'}"
        headers:
          authorization: "Bearer {{access_token}}"
          content-type: "multipart/form-data, boundary=------WebKitFormBoundaryKPzoKfSfBvBzfvZa"

Please advise what i can do

**Comment by hassy** [comment]
A couple of things:

First, the YAML doesn't look right, it should be something like:

```
- post:
    url: "/some/url"
    formData:
      firstName: "Jerry"
      lastName: "Winston"
    headers:
      authorization: "Bearer {{access_token}}"
```

You don't need to specify content type and the boundary manually.

Second, is this a file upload form you're testing? Artillery doesn't support using external files for testing uploads so you'd have to embed the contents of the file directly into the test script.
